<?php
namespace FOA\DomainPayload;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-25 at 11:49:04.
 */
class UpdatedTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Updated
     */
    protected $object;

    /**
     * @var array
     */
    protected $payload;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->payload = array('hello' => 'world', 'another' => 'value');
        $this->object = new Updated($this->payload);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetKey()
    {
        $key = 'hello';
        $expected = 'world';
        $this->assertSame($expected, $this->object->get($key));
    }

    public function testGetKeys()
    {
        $this->assertSame($this->payload, $this->object->get());
    }
}
